/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_2SlurpeeMachine;

import javax.swing.JOptionPane;

/**
 *
 * @author k.gandhi
 */
public class SlurpeeMachine extends javax.swing.JFrame {

    /**
     * Creates new form SlurpeeMachine
     */
    public SlurpeeMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectionSlider = new javax.swing.JSlider();
        FlavourLabel = new javax.swing.JLabel();
        smallButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        largeButton = new javax.swing.JButton();
        xtraLargeButton = new javax.swing.JButton();
        purchaseSlurpeeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsScanned = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slurpee Machine");

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "7-11 Convenience", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT", 1, 30), new java.awt.Color(204, 0, 0))); // NOI18N

        selectionSlider.setForeground(new java.awt.Color(102, 102, 102));
        selectionSlider.setMajorTickSpacing(1);
        selectionSlider.setMaximum(4);
        selectionSlider.setMinimum(1);
        selectionSlider.setSnapToTicks(true);
        selectionSlider.setAlignmentX(1.0F);

        FlavourLabel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        FlavourLabel.setText("Choose Your Flavour:");

        smallButton.setText("SMALL");
        smallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallButtonActionPerformed(evt);
            }
        });

        mediumButton.setText("MEDIUM");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        largeButton.setText("LARGE");
        largeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeButtonActionPerformed(evt);
            }
        });

        xtraLargeButton.setText("X-LARGE");
        xtraLargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtraLargeButtonActionPerformed(evt);
            }
        });

        purchaseSlurpeeButton.setBackground(new java.awt.Color(255, 255, 0));
        purchaseSlurpeeButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        purchaseSlurpeeButton.setText("Purchase Slurpee");
        purchaseSlurpeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseSlurpeeButtonActionPerformed(evt);
            }
        });

        itemsScanned.setColumns(20);
        itemsScanned.setFont(new java.awt.Font("Monotype Corsiva", 0, 13)); // NOI18N
        itemsScanned.setRows(5);
        jScrollPane1.setViewportView(itemsScanned);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_2SlurpeeMachine/slurpees.jpg"))); // NOI18N

        checkOutButton.setBackground(new java.awt.Color(0, 255, 255));
        checkOutButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        checkOutButton.setText("Checkout");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel1.setText("Blue");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setText("Lime");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel5.setText("Grape");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel6.setText("Cherry");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel3.setText("Raspberry");

        sizeLabel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        sizeLabel.setText("Select Your Size:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel4)
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchaseSlurpeeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sizeLabel)
                        .addComponent(FlavourLabel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smallButton)
                                .addGap(32, 32, 32)
                                .addComponent(mediumButton)
                                .addGap(33, 33, 33)
                                .addComponent(largeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xtraLargeButton))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(checkOutButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(selectionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlavourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(smallButton)
                        .addComponent(mediumButton)
                        .addComponent(largeButton)
                        .addComponent(xtraLargeButton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(purchaseSlurpeeButton)
                                .addGap(90, 90, 90))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutButton)
                        .addGap(90, 90, 90))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xtraLargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtraLargeButtonActionPerformed
        size = "X-Large";
        price = 2.00;
    }//GEN-LAST:event_xtraLargeButtonActionPerformed

    private void largeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeButtonActionPerformed
        size = "Large";
        price = 1.75;
    }//GEN-LAST:event_largeButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        size = "Medium";
        price = 1.50;
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void smallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallButtonActionPerformed
        size = "Small";
        price = 1.25;
    }//GEN-LAST:event_smallButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        itemsScanned.setText("");
        JOptionPane.showMessageDialog(null, "The total cost of the slurpees is $" + total + ".");
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void purchaseSlurpeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseSlurpeeButtonActionPerformed
        String flavour = "Lime";
        int tempValue = selectionSlider.getValue();
        if (tempValue == 1) {
            flavour = "Lime";
        } else if (tempValue == 2) {
            flavour = "Grape";
        } else if (tempValue == 3) {
            flavour = "Cherry";
        } else if (tempValue == 4) {
            flavour = "Blue Raspberry";
        }
        total += price;
        itemsScanned.append(size + " " + flavour + " Slurpee $" + price + "\n");
    }//GEN-LAST:event_purchaseSlurpeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlurpeeMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlurpeeMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlurpeeMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlurpeeMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlurpeeMachine().setVisible(true);
            }
        });
    }

    String size = "";
    double price = 0;
    double total = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlavourLabel;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTextArea itemsScanned;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton largeButton;
    private javax.swing.JButton mediumButton;
    private javax.swing.JButton purchaseSlurpeeButton;
    private javax.swing.JSlider selectionSlider;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JButton smallButton;
    private javax.swing.JButton xtraLargeButton;
    // End of variables declaration//GEN-END:variables
}
